// Code generated by scripts/gen_bedrock.py; DO NOT EDIT.
// Sources: GeyserMC/mappings @2f0a8da2 (Java 1.21.11) + Geyser core
// bedrock/ resources (Bedrock 1.26.30) + mcmeta 1.21.11 registries. MIT.

package gw

// bannerBaseRanges: block-state ranges of the banner blocks and their dye
// colour (Java dye id: white 0 … black 15).
var bannerBaseRanges = []struct {
	Min, Max uint32
	Color    int32
}{
	{12725, 12740, 0},  // white_banner
	{12741, 12756, 1},  // orange_banner
	{12757, 12772, 2},  // magenta_banner
	{12773, 12788, 3},  // light_blue_banner
	{12789, 12804, 4},  // yellow_banner
	{12805, 12820, 5},  // lime_banner
	{12821, 12836, 6},  // pink_banner
	{12837, 12852, 7},  // gray_banner
	{12853, 12868, 8},  // light_gray_banner
	{12869, 12884, 9},  // cyan_banner
	{12885, 12900, 10}, // purple_banner
	{12901, 12916, 11}, // blue_banner
	{12917, 12932, 12}, // brown_banner
	{12933, 12948, 13}, // green_banner
	{12949, 12964, 14}, // red_banner
	{12965, 12980, 15}, // black_banner
	{12981, 12984, 0},  // white_wall_banner
	{12985, 12988, 1},  // orange_wall_banner
	{12989, 12992, 2},  // magenta_wall_banner
	{12993, 12996, 3},  // light_blue_wall_banner
	{12997, 13000, 4},  // yellow_wall_banner
	{13001, 13004, 5},  // lime_wall_banner
	{13005, 13008, 6},  // pink_wall_banner
	{13009, 13012, 7},  // gray_wall_banner
	{13013, 13016, 8},  // light_gray_wall_banner
	{13017, 13020, 9},  // cyan_wall_banner
	{13021, 13024, 10}, // purple_wall_banner
	{13025, 13028, 11}, // blue_wall_banner
	{13029, 13032, 12}, // brown_wall_banner
	{13033, 13036, 13}, // green_wall_banner
	{13037, 13040, 14}, // red_wall_banner
	{13041, 13044, 15}, // black_wall_banner
}
