// Code generated by scripts/gen_bedrock.py; DO NOT EDIT.
// Sources: GeyserMC/mappings @0fd435d3 (Java 26.2) + Geyser core
// bedrock/ resources (Bedrock 1.26.50), MIT; vanilla 26.3 reports.

package gw

// bannerBaseRanges: block-state ranges of the banner blocks and their dye
// colour (Java dye id: white 0 … black 15).
var bannerBaseRanges = []struct {
	Min, Max uint32
	Color    int32
}{
	{14774, 14789, 0},  // white_banner
	{14790, 14805, 1},  // orange_banner
	{14806, 14821, 2},  // magenta_banner
	{14822, 14837, 3},  // light_blue_banner
	{14838, 14853, 4},  // yellow_banner
	{14854, 14869, 5},  // lime_banner
	{14870, 14885, 6},  // pink_banner
	{14886, 14901, 7},  // gray_banner
	{14902, 14917, 8},  // light_gray_banner
	{14918, 14933, 9},  // cyan_banner
	{14934, 14949, 10}, // purple_banner
	{14950, 14965, 11}, // blue_banner
	{14966, 14981, 12}, // brown_banner
	{14982, 14997, 13}, // green_banner
	{14998, 15013, 14}, // red_banner
	{15014, 15029, 15}, // black_banner
	{15030, 15033, 0},  // white_wall_banner
	{15034, 15037, 1},  // orange_wall_banner
	{15038, 15041, 2},  // magenta_wall_banner
	{15042, 15045, 3},  // light_blue_wall_banner
	{15046, 15049, 4},  // yellow_wall_banner
	{15050, 15053, 5},  // lime_wall_banner
	{15054, 15057, 6},  // pink_wall_banner
	{15058, 15061, 7},  // gray_wall_banner
	{15062, 15065, 8},  // light_gray_wall_banner
	{15066, 15069, 9},  // cyan_wall_banner
	{15070, 15073, 10}, // purple_wall_banner
	{15074, 15077, 11}, // blue_wall_banner
	{15078, 15081, 12}, // brown_wall_banner
	{15082, 15085, 13}, // green_wall_banner
	{15086, 15089, 14}, // red_wall_banner
	{15090, 15093, 15}, // black_wall_banner
}
